### PR TITLE
Add field for animal type

### PR DESCRIPTION
**Pull request by ruralocity**
Here's a quick field/association for animal type (issue #2 ). Does this method of seeding data work for you?

### CODE REVIEW

**Comment by mcary** [comment]
I wasn't expecting an association; I'd have been happy with just a string field in the database.  But I think this will do.  I'm gonna check this out locally before merging.

**Comment by mcary** [comment]
Hrm... at a minimum, the label is wrong (summary instead of animal type).

image

But I'm also concerned about:
- Somehow I envisioned a select.  I guess I'm just thinking in terms of keeping the form small on the screen.  Not sure that's critical.
- Also, without the seed, no radios were rendered, which is a confusing state, so it should be mentioned in the readme as part of setup.

I don't normally think of seed data as being idempotent.  I would normally only run "rake db:seed" for a new empty database and expect db:migrate to populate newly added lookup tables.  But since it _is_ idempotent and the first seed, it's not really an issue.

**Comment by mcary** [comment]
Looks like there is missing nil handling for the delegation and no upgrade for existing records:

image

Also happens on /reports/1.

**Comment by ruralocity** [comment]
Your call on select vs. radio. I don't like selects on iOS because it takes you to a separate part of the screen and Apple's silly roller UI elements. Not sure about Android or others. I've seen Bootstrap plugins to do a faux select from a radio group, but I've never used any of them.

I can fix the other two issues (missing nil check on delegate and README for seed data) unless you want to back out of that and go with a string vs. an association. I've found myself going the association route almost by default now because inevitably I want to do something more with the data in whatever I'm working on; might not apply here.

**Comment by mcary** [comment]
Yeah, I hear ya on the association.  My main issue is with the actual show-stopping bugs: wrong label and null animal exception.  If you're not online, I might try to work through this tonight.  It's a high prio right now.

**Comment by ruralocity** [comment]
Sorry I couldn't get to it last night—weather-related internet flakiness.

**Pull request merged**
